export const countries = [
  { key: "ad", name: "Andorra", dialCode: "+376", maxLength: 9 },
  { key: "ae", name: "United Arab Emirates", dialCode: "+971", maxLength: 9 },
  { key: "af", name: "Afghanistan", dialCode: "+93", maxLength: 9 },
  { key: "ag", name: "Antigua & Barbuda", dialCode: "+1-268", maxLength: 10 },
  { key: "ai", name: "Anguilla", dialCode: "+1-264", maxLength: 10 },
  { key: "al", name: "Albania", dialCode: "+355", maxLength: 9 },
  { key: "am", name: "Armenia", dialCode: "+374", maxLength: 8 },
  { key: "ao", name: "Angola", dialCode: "+244", maxLength: 9 },
  { key: "ar", name: "Argentina", dialCode: "+54", maxLength: 10 },
  { key: "as", name: "American Samoa", dialCode: "+1-684", maxLength: 10 },
  { key: "at", name: "Austria", dialCode: "+43", maxLength: 10 },
  { key: "au", name: "Australia", dialCode: "+61", maxLength: 9 },
  { key: "aw", name: "Aruba", dialCode: "+297", maxLength: 7 },
  { key: "ax", name: "Åland Islands", dialCode: "+358", maxLength: 10 },
  { key: "az", name: "Azerbaijan", dialCode: "+994", maxLength: 9 },
  { key: "ba", name: "Bosnia & Herzegovina", dialCode: "+387", maxLength: 8 },
  { key: "bb", name: "Barbados", dialCode: "+1-246", maxLength: 10 },
  { key: "bd", name: "Bangladesh", dialCode: "+880", maxLength: 10 },
  { key: "be", name: "Belgium", dialCode: "+32", maxLength: 9 },
  { key: "bf", name: "Burkina Faso", dialCode: "+226", maxLength: 8 },
  { key: "bg", name: "Bulgaria", dialCode: "+359", maxLength: 9 },
  { key: "bh", name: "Bahrain", dialCode: "+973", maxLength: 8 },
  { key: "bi", name: "Burundi", dialCode: "+257", maxLength: 8 },
  { key: "bj", name: "Benin", dialCode: "+229", maxLength: 8 },
  { key: "bm", name: "Bermuda", dialCode: "+1-441", maxLength: 10 },
  { key: "bn", name: "Brunei", dialCode: "+673", maxLength: 7 },
  { key: "bo", name: "Bolivia", dialCode: "+591", maxLength: 8 },
  { key: "br", name: "Brazil", dialCode: "+55", maxLength: 11 },
  { key: "bs", name: "Bahamas", dialCode: "+1-242", maxLength: 10 },
  { key: "bt", name: "Bhutan", dialCode: "+975", maxLength: 8 },
  { key: "bw", name: "Botswana", dialCode: "+267", maxLength: 8 },
  { key: "by", name: "Belarus", dialCode: "+375", maxLength: 9 },
  { key: "bz", name: "Belize", dialCode: "+501", maxLength: 7 },
  { key: "ca", name: "Canada", dialCode: "+1", maxLength: 10 },
  { key: "cd", name: "Congo (DRC)", dialCode: "+243", maxLength: 9 },
  { key: "cf", name: "Central African Republic", dialCode: "+236", maxLength: 8 },
  { key: "cg", name: "Congo (ROC)", dialCode: "+242", maxLength: 9 },
  { key: "ch", name: "Switzerland", dialCode: "+41", maxLength: 9 },
  { key: "ci", name: "Côte d’Ivoire", dialCode: "+225", maxLength: 8 },
  { key: "cl", name: "Chile", dialCode: "+56", maxLength: 9 },
  { key: "cm", name: "Cameroon", dialCode: "+237", maxLength: 9 },
  { key: "cn", name: "China", dialCode: "+86", maxLength: 11 },
  { key: "co", name: "Colombia", dialCode: "+57", maxLength: 10 },
  { key: "cr", name: "Costa Rica", dialCode: "+506", maxLength: 8 },
  { key: "cu", name: "Cuba", dialCode: "+53", maxLength: 8 },
  { key: "cv", name: "Cape Verde", dialCode: "+238", maxLength: 7 },
  { key: "cy", name: "Cyprus", dialCode: "+357", maxLength: 8 },
  { key: "cz", name: "Czechia", dialCode: "+420", maxLength: 9 },
  { key: "de", name: "Germany", dialCode: "+49", maxLength: 11 },
  { key: "dj", name: "Djibouti", dialCode: "+253", maxLength: 8 },
  { key: "dk", name: "Denmark", dialCode: "+45", maxLength: 8 },
  { key: "dm", name: "Dominica", dialCode: "+1-767", maxLength: 10 },
  { key: "do", name: "Dominican Republic", dialCode: "+1-809", maxLength: 10 },
  { key: "dz", name: "Algeria", dialCode: "+213", maxLength: 9 },
  { key: "ec", name: "Ecuador", dialCode: "+593", maxLength: 9 },
  { key: "ee", name: "Estonia", dialCode: "+372", maxLength: 8 },
  { key: "eg", name: "Egypt", dialCode: "+20", maxLength: 10 },
  { key: "er", name: "Eritrea", dialCode: "+291", maxLength: 7 },
  { key: "es", name: "Spain", dialCode: "+34", maxLength: 9 },
  { key: "et", name: "Ethiopia", dialCode: "+251", maxLength: 9 },
  { key: "fi", name: "Finland", dialCode: "+358", maxLength: 10 },
  { key: "fj", name: "Fiji", dialCode: "+679", maxLength: 7 },
  { key: "fm", name: "Micronesia", dialCode: "+691", maxLength: 7 },
  { key: "fr", name: "France", dialCode: "+33", maxLength: 9 },
  { key: "ga", name: "Gabon", dialCode: "+241", maxLength: 8 },
  { key: "gb", name: "United Kingdom", dialCode: "+44", maxLength: 10 },
  { key: "gd", name: "Grenada", dialCode: "+1-473", maxLength: 10 },
  { key: "ge", name: "Georgia", dialCode: "+995", maxLength: 9 },
  { key: "gh", name: "Ghana", dialCode: "+233", maxLength: 9 },
  { key: "gm", name: "Gambia", dialCode: "+220", maxLength: 7 },
  { key: "gn", name: "Guinea", dialCode: "+224", maxLength: 9 },
  { key: "gq", name: "Equatorial Guinea", dialCode: "+240", maxLength: 9 },
  { key: "gr", name: "Greece", dialCode: "+30", maxLength: 10 },
  { key: "gt", name: "Guatemala", dialCode: "+502", maxLength: 8 },
  { key: "gw", name: "Guinea-Bissau", dialCode: "+245", maxLength: 7 },
  { key: "gy", name: "Guyana", dialCode: "+592", maxLength: 7 },
  { key: "hn", name: "Honduras", dialCode: "+504", maxLength: 8 },
  { key: "hr", name: "Croatia", dialCode: "+385", maxLength: 9 },
  { key: "ht", name: "Haiti", dialCode: "+509", maxLength: 8 },
  { key: "hu", name: "Hungary", dialCode: "+36", maxLength: 9 },
  { key: "id", name: "Indonesia", dialCode: "+62", maxLength: 11 },
  { key: "ie", name: "Ireland", dialCode: "+353", maxLength: 9 },
  { key: "il", name: "Israel", dialCode: "+972", maxLength: 9 },
  { key: "in", name: "India", dialCode: "+91", maxLength: 10 },
  { key: "iq", name: "Iraq", dialCode: "+964", maxLength: 10 },
  { key: "ir", name: "Iran", dialCode: "+98", maxLength: 10 },
  { key: "is", name: "Iceland", dialCode: "+354", maxLength: 7 },
  { key: "it", name: "Italy", dialCode: "+39", maxLength: 10 },
  { key: "jm", name: "Jamaica", dialCode: "+1-876", maxLength: 10 },
  { key: "jo", name: "Jordan", dialCode: "+962", maxLength: 9 },
  { key: "jp", name: "Japan", dialCode: "+81", maxLength: 10 },
  { key: "ke", name: "Kenya", dialCode: "+254", maxLength: 9 },
  { key: "kg", name: "Kyrgyzstan", dialCode: "+996", maxLength: 9 },
  { key: "kh", name: "Cambodia", dialCode: "+855", maxLength: 9 },
  { key: "ki", name: "Kiribati", dialCode: "+686", maxLength: 7 },
  { key: "km", name: "Comoros", dialCode: "+269", maxLength: 7 },
  { key: "kn", name: "St. Kitts & Nevis", dialCode: "+1-869", maxLength: 10 },
  { key: "kp", name: "North Korea", dialCode: "+850", maxLength: 9 },
  { key: "kr", name: "South Korea", dialCode: "+82", maxLength: 10 },
  { key: "kw", name: "Kuwait", dialCode: "+965", maxLength: 8 },
  { key: "ky", name: "Cayman Islands", dialCode: "+1-345", maxLength: 10 },
  { key: "kz", name: "Kazakhstan", dialCode: "+7", maxLength: 10 },
  { key: "la", name: "Laos", dialCode: "+856", maxLength: 9 },
  { key: "lb", name: "Lebanon", dialCode: "+961", maxLength: 8 },
  { key: "lc", name: "Saint Lucia", dialCode: "+1-758", maxLength: 10 },
  { key: "li", name: "Liechtenstein", dialCode: "+423", maxLength: 7 },
  { key: "lk", name: "Sri Lanka", dialCode: "+94", maxLength: 9 },
  { key: "lr", name: "Liberia", dialCode: "+231", maxLength: 7 },
  { key: "ls", name: "Lesotho", dialCode: "+266", maxLength: 8 },
  { key: "lt", name: "Lithuania", dialCode: "+370", maxLength: 8 },
  { key: "lu", name: "Luxembourg", dialCode: "+352", maxLength: 9 },
  { key: "lv", name: "Latvia", dialCode: "+371", maxLength: 8 },
  { key: "ly", name: "Libya", dialCode: "+218", maxLength: 9 },
  { key: "ma", name: "Morocco", dialCode: "+212", maxLength: 9 },
  { key: "mc", name: "Monaco", dialCode: "+377", maxLength: 8 },
  { key: "md", name: "Moldova", dialCode: "+373", maxLength: 8 },
  { key: "me", name: "Montenegro", dialCode: "+382", maxLength: 8 },
  { key: "mg", name: "Madagascar", dialCode: "+261", maxLength: 9 },
  { key: "mh", name: "Marshall Islands", dialCode: "+692", maxLength: 7 },
  { key: "mk", name: "North Macedonia", dialCode: "+389", maxLength: 8 },
  { key: "ml", name: "Mali", dialCode: "+223", maxLength: 8 },
  { key: "mm", name: "Myanmar", dialCode: "+95", maxLength: 9 },
  { key: "mn", name: "Mongolia", dialCode: "+976", maxLength: 8 },
  { key: "mo", name: "Macau", dialCode: "+853", maxLength: 8 },
  { key: "mr", name: "Mauritania", dialCode: "+222", maxLength: 8 },
  { key: "ms", name: "Montserrat", dialCode: "+1-664", maxLength: 10 },
  { key: "mt", name: "Malta", dialCode: "+356", maxLength: 8 },
  { key: "mu", name: "Mauritius", dialCode: "+230", maxLength: 8 },
  { key: "mv", name: "Maldives", dialCode: "+960", maxLength: 7 },
  { key: "mw", name: "Malawi", dialCode: "+265", maxLength: 9 },
  { key: "mx", name: "Mexico", dialCode: "+52", maxLength: 10 },
  { key: "my", name: "Malaysia", dialCode: "+60", maxLength: 10 },
  { key: "mz", name: "Mozambique", dialCode: "+258", maxLength: 9 },
  { key: "na", name: "Namibia", dialCode: "+264", maxLength: 9 },
  { key: "ne", name: "Niger", dialCode: "+227", maxLength: 8 },
  { key: "ng", name: "Nigeria", dialCode: "+234", maxLength: 10 },
  { key: "ni", name: "Nicaragua", dialCode: "+505", maxLength: 8 },
  { key: "nl", name: "Netherlands", dialCode: "+31", maxLength: 9 },
  { key: "no", name: "Norway", dialCode: "+47", maxLength: 8 },
  { key: "np", name: "Nepal", dialCode: "+977", maxLength: 10 },
  { key: "nr", name: "Nauru", dialCode: "+674", maxLength: 7 },
  { key: "nz", name: "New Zealand", dialCode: "+64", maxLength: 9 },
  { key: "om", name: "Oman", dialCode: "+968", maxLength: 8 },
  { key: "pa", name: "Panama", dialCode: "+507", maxLength: 8 },
  { key: "pe", name: "Peru", dialCode: "+51", maxLength: 9 },
  { key: "pg", name: "Papua New Guinea", dialCode: "+675", maxLength: 8 },
  { key: "ph", name: "Philippines", dialCode: "+63", maxLength: 10 },
  { key: "pk", name: "Pakistan", dialCode: "+92", maxLength: 10 },
  { key: "pl", name: "Poland", dialCode: "+48", maxLength: 9 },
  { key: "pt", name: "Portugal", dialCode: "+351", maxLength: 9 },
  { key: "py", name: "Paraguay", dialCode: "+595", maxLength: 9 },
  { key: "qa", name: "Qatar", dialCode: "+974", maxLength: 8 },
  { key: "ro", name: "Romania", dialCode: "+40", maxLength: 9 },
  { key: "rs", name: "Serbia", dialCode: "+381", maxLength: 9 },
  { key: "ru", name: "Russia", dialCode: "+7", maxLength: 10 },
  { key: "rw", name: "Rwanda", dialCode: "+250", maxLength: 9 },
  { key: "sa", name: "Saudi Arabia", dialCode: "+966", maxLength: 9 },
{ key: "sb", name: "Solomon Islands", dialCode: "+677", maxLength: 7 },
{ key: "sc", name: "Seychelles", dialCode: "+248", maxLength: 7 },
{ key: "sd", name: "Sudan", dialCode: "+249", maxLength: 9 },
{ key: "se", name: "Sweden", dialCode: "+46", maxLength: 10 },
{ key: "sg", name: "Singapore", dialCode: "+65", maxLength: 8 },
{ key: "si", name: "Slovenia", dialCode: "+386", maxLength: 8 },
{ key: "sk", name: "Slovakia", dialCode: "+421", maxLength: 9 },
{ key: "sl", name: "Sierra Leone", dialCode: "+232", maxLength: 8 },
{ key: "sn", name: "Senegal", dialCode: "+221", maxLength: 9 },
{ key: "so", name: "Somalia", dialCode: "+252", maxLength: 8 },
{ key: "sr", name: "Suriname", dialCode: "+597", maxLength: 7 },
{ key: "st", name: "Sao Tome & Principe", dialCode: "+239", maxLength: 7 },
{ key: "sv", name: "El Salvador", dialCode: "+503", maxLength: 8 },
{ key: "sy", name: "Syria", dialCode: "+963", maxLength: 9 },
{ key: "sz", name: "Eswatini", dialCode: "+268", maxLength: 7 },
{ key: "td", name: "Chad", dialCode: "+235", maxLength: 8 },
{ key: "tg", name: "Togo", dialCode: "+228", maxLength: 8 },
{ key: "th", name: "Thailand", dialCode: "+66", maxLength: 9 },
{ key: "tj", name: "Tajikistan", dialCode: "+992", maxLength: 9 },
{ key: "tl", name: "Timor-Leste", dialCode: "+670", maxLength: 7 },
{ key: "tm", name: "Turkmenistan", dialCode: "+993", maxLength: 8 },
{ key: "tn", name: "Tunisia", dialCode: "+216", maxLength: 8 },
{ key: "to", name: "Tonga", dialCode: "+676", maxLength: 7 },
{ key: "tr", name: "Turkey", dialCode: "+90", maxLength: 10 },
{ key: "tt", name: "Trinidad & Tobago", dialCode: "+1-868", maxLength: 10 },
{ key: "tv", name: "Tuvalu", dialCode: "+688", maxLength: 7 },
{ key: "tw", name: "Taiwan", dialCode: "+886", maxLength: 9 },
{ key: "tz", name: "Tanzania", dialCode: "+255", maxLength: 9 },
{ key: "ua", name: "Ukraine", dialCode: "+380", maxLength: 9 },
{ key: "ug", name: "Uganda", dialCode: "+256", maxLength: 9 },
{ key: "us", name: "United States", dialCode: "+1", maxLength: 10 },
{ key: "uy", name: "Uruguay", dialCode: "+598", maxLength: 8 },
{ key: "uz", name: "Uzbekistan", dialCode: "+998", maxLength: 9 },
{ key: "vc", name: "St. Vincent & Grenadines", dialCode: "+1-784", maxLength: 10 },
{ key: "ve", name: "Venezuela", dialCode: "+58", maxLength: 10 },
{ key: "vg", name: "British Virgin Islands", dialCode: "+1-284", maxLength: 10 },
{ key: "vi", name: "U.S. Virgin Islands", dialCode: "+1-340", maxLength: 10 },
{ key: "vn", name: "Vietnam", dialCode: "+84", maxLength: 9 },
{ key: "vu", name: "Vanuatu", dialCode: "+678", maxLength: 7 },
{ key: "ws", name: "Samoa", dialCode: "+685", maxLength: 7 },
{ key: "ye", name: "Yemen", dialCode: "+967", maxLength: 9 },
{ key: "za", name: "South Africa", dialCode: "+27", maxLength: 9 },
{ key: "zm", name: "Zambia", dialCode: "+260", maxLength: 9 },
{ key: "zw", name: "Zimbabwe", dialCode: "+263", maxLength: 9 },
];

export const countryCodes: Record<string, string> = Object.fromEntries(
  countries.map((c) => [c.key, c.dialCode])
);
