export interface Job {
  id: number
  company: string
  logo: string
  logoImg?: string
  logoColor: string
  isNew: boolean
  isFeatured: boolean
  position: string
  postedAt: string
  contract: string
  location: string
  languages: string[]
  tools: string[]
  role?: string
  level?: string
}

export const jobsData: Job[] = [
  {
    id: 1,
    company: "Photosnap",
    logo: "PHOTOSNAP",
    logoImg: "/img/photosnap.svg",
    logoColor: "#000000",
    isNew: true,
    isFeatured: true,
    position: "Senior Frontend Developer",
    role: "Frontend",
    level: "Senior",
    postedAt: "1d ago",
    contract: "Full Time",
    location: "USA only",
    languages: ["HTML", "CSS", "JavaScript"],
    tools: [],
  },
  {
    id: 2,
    company: "Manage",
    logo: "manage",
    logoImg: "/img/manage.svg",
    logoColor: "#E07453",
    isNew: true,
    isFeatured: true,
    position: "Fullstack Developer",
    role: "Fullstack",
    level: "Midweight",
    postedAt: "1d ago",
    contract: "Part Time",
    location: "Remote",
    languages: ["Python"],
    tools: ["React"],
  },
  {
    id: 3,
    company: "Account",
    logo: "ACCOUNT",
    logoImg: "/img/account.svg",
    logoColor: "#5A1CB0",
    isNew: true,
    isFeatured: false,
    position: "Junior Frontend Developer",
    role: "Frontend",
    level: "Junior",
    postedAt: "2d ago",
    contract: "Part Time",
    location: "USA only",
    languages: ["JavaScript"],
    tools: ["React", "Sass"],
  },
  {
    id: 4,
    company: "MyHome",
    logo: "MYHOME",
    logoImg: "/img/myhome.svg",
    logoColor: "#7BA5A5",
    isNew: false,
    isFeatured: false,
    position: "Junior Frontend Developer",
    role: "Frontend",
    level: "Junior",
    postedAt: "5d ago",
    contract: "Contract",
    location: "USA only",
    languages: ["CSS", "JavaScript"],
    tools: [],
  },
  {
    id: 5,
    company: "Loop Studios",
    logo: "LOOP\nSTUDIOS",
    logoImg: "/img/loop-studios.svg",
    logoColor: "#9E2158",
    isNew: false,
    isFeatured: false,
    position: "Software Engineer",
    role: "Fullstack",
    level: "Midweight",
    postedAt: "1w ago",
    contract: "Full Time",
    location: "Worldwide",
    languages: ["JavaScript", "Ruby", "Sass"],
    tools: [],
  },
  {
    id: 6,
    company: "FaceIt",
    logo: "FaceIt",
    logoImg: "/img/faceit.svg",
    logoColor: "#7E63E3",
    isNew: false,
    isFeatured: false,
    position: "Junior Backend Developer",
    role: "Backend",
    level: "Junior",
    postedAt: "2w ago",
    contract: "Full Time",
    location: "UK only",
    languages: ["Ruby", "RoR"],
    tools: [],
  },
  {
    id: 7,
    company: "Shortly",
    logo: "shortly",
    logoImg: "/img/shortly.svg",
    logoColor: "#29B9CC",
    isNew: false,
    isFeatured: false,
    position: "Junior Developer",
    role: "Frontend",
    level: "Junior",
    postedAt: "2w ago",
    contract: "Full Time",
    location: "Worldwide",
    languages: ["HTML", "JavaScript", "Sass"],
    tools: [],
  },
  {
    id: 8,
    company: "Insure",
    logo: "INSURE",
    logoImg: "/img/insure.svg",
    logoColor: "#2E3A46",
    isNew: false,
    isFeatured: false,
    position: "Junior Frontend Developer",
    role: "Frontend",
    level: "Junior",
    postedAt: "2w ago",
    contract: "Full Time",
    location: "USA only",
    languages: ["JavaScript"],
    tools: ["Vue", "Sass"],
  },
  {
    id: 9,
    company: "Eyecam Co.",
    logo: "EYECAM",
    logoImg: "/img/eyecam-co.svg",
    logoColor: "#2889AF",
    isNew: false,
    isFeatured: false,
    position: "Full Stack Engineer",
    role: "Fullstack",
    level: "Midweight",
    postedAt: "3w ago",
    contract: "Full Time",
    location: "Worldwide",
    languages: ["JavaScript", "Python"],
    tools: ["Django"],
  },
  {
    id: 10,
    company: "The Air Filter Company",
    logo: "The Air\nFilter Co.",
    logoImg: "/img/the-air-filter-company.svg",
    logoColor: "#1C5F5F",
    isNew: false,
    isFeatured: false,
    position: "Front-end Dev",
    role: "Frontend",
    level: "Junior",
    postedAt: "1mo ago",
    contract: "Part Time",
    location: "Worldwide",
    languages: ["JavaScript"],
    tools: ["React", "Sass"],
  },
]
