export const AUCTION_ITEMS = [
  {
    id: "kia-carnival",
    name: "Kia Carnival",
    image: "/blue-kia-carnival-minivan.png",
    price: "$1,07899.99",
    currentBid: "$1,07899.99",
    rating: 5,
    description: "Lorem ipsum dolor sit amet consectetur. Velit amet pretium leo mauris. Molestudunt dignissim tortor elit mauris pretium tincidunt libero. Suspendisse aliquam donec leo nisl purus et quam pulvinar. Odio egestas egestas tristique et lectus viverra in sed mauris.",
    timeRemaining: "06:00pm 03 Jan 2023",
    endType: "End Time",
    status: "trending",
  },
  {
    id: "range-rover",
    name: "Range Rover",
    image: "/white-range-rover-suv.png",
    price: "$1,07899.99",
    currentBid: "$1,07899.99",
    rating: 5,
    description: "Lorem ipsum dolor sit amet consectetur. Velit amet pretium leo mauris. Molestudunt dignissim tortor elit mauris pretium tincidunt libero. Suspendisse aliquam donec leo nisl purus et quam pulvinar. Odio egestas egestas tristique et lectus viverra in sed mauris.",
    timeRemaining: "06:00pm 03 Jan 2023",
    endType: "End Time",
  },
  {
    id: "bentley",
    name: "Bentley",
    image: "/blue-bentley-luxury-sedan.png",
    price: "$1,07899.99",
    currentBid: "$1,07899.99",
    rating: 5,
    description: "Lorem ipsum dolor sit amet consectetur. Velit amet pretium leo mauris. Molestudunt dignissim tortor elit mauris pretium tincidunt libero. Suspendisse aliquam donec leo nisl purus et quam pulvinar. Odio egestas egestas tristique et lectus viverra in sed mauris.",
    timeRemaining: "06:00pm 03 Jan 2023",
    endType: "End Time",
  },
  {
    id: "hyundai-verna",
    name: "Hyundai Verna",
    image: "/white-hyundai-verna-sedan.png",
    price: "$1,07899.99",
    currentBid: "$1,07899.99",
    rating: 5,
    description: "Lorem ipsum dolor sit amet consectetur. Velit amet pretium leo mauris. Molestudunt dignissim tortor elit mauris pretium tincidunt libero. Suspendisse aliquam donec leo nisl purus et quam pulvinar. Odio egestas egestas tristique et lectus viverra in sed mauris.",
    timeRemaining: "06:00pm 03 Jan 2023",
    endType: "End Time",
  },
  {
    id: "mahindra-thar",
    name: "Mahindra Thar",
    image: "/red-mahindra-thar-suv.png",
    price: "$1,07899.99",
    currentBid: "$1,07899.99",
    rating: 5,
    description: "Lorem ipsum dolor sit amet consectetur. Velit amet pretium leo mauris. Molestudunt dignissim tortor elit mauris pretium tincidunt libero. Suspendisse aliquam donec leo nisl purus et quam pulvinar. Odio egestas egestas tristique et lectus viverra in sed mauris.",
    timeRemaining: "06:00pm 03 Jan 2023",
    endType: "End Time",
    status: "trending",
  },
  {
    id: "ferrari",
    name: "Ferrari",
    image: "/yellow-ferrari-sports-car.png",
    price: "$1,07899.99",
    currentBid: "$1,07899.99",
    rating: 5,
    description: "Lorem ipsum dolor sit amet consectetur. Velit amet pretium leo mauris. Molestudunt dignissim tortor elit mauris pretium tincidunt libero. Suspendisse aliquam donec leo nisl purus et quam pulvinar. Odio egestas egestas tristique et lectus viverra in sed mauris.",
    timeRemaining: "06:00pm 03 Jan 2023",
    endType: "End Time",
  },
];