export const CAR_AUCTION_ITEMS = [
  {
    id: "1",
    name: "Kia Carnival",
    image: "/kia-carnival.png",
    price: "$1,07899.99",
    totalBids: 130,
    timeLeft: { days: 31, hours: 20, minutes: 40, seconds: 25 },
    endTime: "06:00pm 03 Jan 2023",
    rating: 5,
    description: "Lorem ipsum dolor sit amet consectetur. Velit amet aenean sed nunc. Malesuada dignissim viverra praesent aenean nulla mattiszzxzxzxz....",
    status: "trending" as const,
  },
  {
    id: "2",
    name: "Range Rover",
    image: "/white-range-rover-main.png",
    price: "$1,07899.99",
    totalBids: 130,
    timeLeft: { days: 31, hours: 20, minutes: 40, seconds: 25 },
    endTime: "06:00pm 03 Jan 2023",
    rating: 5,
    description: "Lorem ipsum dolor sit amet consectetur. Velit amet aenean sed nunc. Malesuada dignissim viverra praesent aenean nulla mattiszzxzxzxz....",
    status: "trending" as const,
  },
  {
    id: "3",
    name: "Bently",
    image: "/bentley-blue.png",
    price: "$1,07899.99",
    totalBids: 130,
    timeLeft: { days: 31, hours: 20, minutes: 40, seconds: 25 },
    endTime: "06:00pm 03 Jan 2023",
    rating: 5,
    description: "Lorem ipsum dolor sit amet consectetur. Velit amet aenean sed nunc. Malesuada dignissim viverra praesent aenean nulla mattiszzxzxzxz....",
    status: null,
  },
  {
    id: "4",
    name: "Hyundai Verna",
    image: "/hyundai-verna.png",
    price: "$1,07899.99",
    totalBids: 130,
    timeLeft: { days: 31, hours: 20, minutes: 40, seconds: 25 },
    endTime: "06:00pm 03 Jan 2023",
    rating: 5,
    description: "Lorem ipsum dolor sit amet consectetur. Velit amet aenean sed nunc. Malesuada dignissim viverra praesent aenean nulla mattiszzxzxzxz....",
    status: null,
  },
  {
    id: "5",
    name: "Mahindra Thar",
    image: "/mahindra-thar.png",
    price: "$1,07899.99",
    totalBids: 130,
    timeLeft: { days: 31, hours: 20, minutes: 40, seconds: 25 },
    endTime: "06:00pm 03 Jan 2023",
    rating: 5,
    description: "Lorem ipsum dolor sit amet consectetur. Velit amet aenean sed nunc. Malesuada dignissim viverra praesent aenean nulla mattiszzxzxzxz....",
    status: "trending" as const,
  },
  {
    id: "6",
    name: "Ferrari",
    image: "/ferrari-yellow.png",
    price: "$1,07899.99",
    totalBids: 130,
    timeLeft: { days: 31, hours: 20, minutes: 40, seconds: 25 },
    endTime: "06:00pm 03 Jan 2023",
    rating: 5,
    description: "Lorem ipsum dolor sit amet consectetur. Velit amet aenean sed nunc. Malesuada dignissim viverra praesent aenean nulla mattiszzxzxzxz....",
    status: null,
  },
  {
    id: "7",
    name: "BMW M4",
    image: "/yellow-bmw-m4-coupe.png",
    price: "$1,07899.99",
    totalBids: 130,
    timeLeft: { days: 31, hours: 20, minutes: 40, seconds: 25 },
    endTime: "06:00pm 03 Jan 2023",
    rating: 5,
    description: "Lorem ipsum dolor sit amet consectetur. Velit amet aenean sed nunc. Malesuada dignissim viverra praesent aenean nulla mattiszzxzxzxz....",
    status: null,
  },
  {
    id: "8",
    name: "Maruti Brezza",
    image: "/maruti-brezza.png",
    price: "$1,07899.99",
    totalBids: 130,
    timeLeft: { days: 31, hours: 20, minutes: 40, seconds: 25 },
    endTime: "06:00pm 03 Jan 2023",
    rating: 5,
    description: "Lorem ipsum dolor sit amet consectetur. Velit amet aenean sed nunc. Malesuada dignissim viverra praesent aenean nulla mattiszzxzxzxz....",
    status: null,
  },
  {
    id: "9",
    name: "Jaguar XF",
    image: "/jaguar-xf.png",
    price: "$1,07899.99",
    totalBids: 130,
    timeLeft: { days: 31, hours: 20, minutes: 40, seconds: 25 },
    endTime: "06:00pm 03 Jan 2023",
    rating: 5,
    description: "Lorem ipsum dolor sit amet consectetur. Velit amet aenean sed nunc. Malesuada dignissim viverra praesent aenean nulla mattiszzxzxzxz....",
    status: null,
  },
  {
    id: "10",
    name: "Tata Tiago",
    image: "/tata-tiago.png",
    price: "$1,07899.99",
    totalBids: 130,
    timeLeft: { days: 31, hours: 20, minutes: 40, seconds: 25 },
    endTime: "06:00pm 03 Jan 2023",
    rating: 5,
    description: "Lorem ipsum dolor sit amet consectetur. Velit amet aenean sed nunc. Malesuada dignissim viverra praesent aenean nulla mattiszzxzxzxz....",
    status: "trending" as const,
  },
];