export const FILTER_OPTIONS = {
  carTypes: [
    { value: "sedan", label: "Sedan" },
    { value: "suv", label: "SUV" },
    { value: "hatchback", label: "Hatchback" },
    { value: "coupe", label: "Coupe" },
    { value: "convertible", label: "Convertible" },
  ],
  colors: [
    { value: "white", label: "White" },
    { value: "black", label: "Black" },
    { value: "red", label: "Red" },
    { value: "blue", label: "Blue" },
    { value: "silver", label: "Silver" },
    { value: "gray", label: "Gray" },
  ],
  makes: [
    { value: "bmw", label: "BMW" },
    { value: "audi", label: "Audi" },
    { value: "mercedes", label: "Mercedes" },
    { value: "toyota", label: "Toyota" },
    { value: "honda", label: "Honda" },
    { value: "ford", label: "Ford" },
    { value: "kia", label: "Kia" },
    { value: "hyundai", label: "Hyundai" },
    { value: "ferrari", label: "Ferrari" },
    { value: "porsche", label: "Porsche" },
  ],
  models: [
    { value: "model1", label: "Model 1" },
    { value: "model2", label: "Model 2" },
    { value: "model3", label: "Model 3" },
    { value: "corolla", label: "Corolla" },
    { value: "civic", label: "Civic" },
    { value: "3series", label: "3 Series" },
  ],
  styles: [
    { value: "luxury", label: "Luxury" },
    { value: "sport", label: "Sport" },
    { value: "classic", label: "Classic" },
    { value: "economy", label: "Economy" },
  ],
  sortOptions: [
    { value: "relevance", label: "Sort by Relevance" },
    { value: "price-low", label: "Price: Low to High" },
    { value: "price-high", label: "Price: High to Low" },
    { value: "newest", label: "Newest First" },
    { value: "oldest", label: "Oldest First" },
  ],
};